from collections import namedtuple


class Point3D:
    def __init__(self, x, y, z):
        self.x = x
        self.y = y
        self.z = z


# named tuple are immutable - nobody can modify that obj
Point2D = namedtuple("Point2D", ["x", "y"])  # we had a class generated by named tuple
pt1 = Point2D(10, 20)
print(pt1)

pt3_1 = Point3D(1, 2, 3)
print(pt3_1)  # print  `<__main__.Point3D object at 0x108dffa60>`, so we have to implement `__repr__`


# example 2
Point2D = namedtuple("Point2D", ("x", "y"))  # we had a class generated by named tuple
pt2 = Point2D(4, 5)
print(pt2)
pt2.x = 100
print(pt2)   # cannot set attribute

